filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: dev
  url: http://chartmuseum-jx.34.82.59.208.nip.io
- name: activiti-cloud-charts
  url: https://github.com/Activiti/activiti-cloud-full-chart
releases:
- chart: jxgh/jx-verify
  name: jx-verify
  namespace: jx-staging
  values:
  - jx-values.yaml
- chart: dev/nodetest
  version: 0.0.1
  name: nodetest
  namespace: jx-staging
  values:
  - jx-values.yaml
- chart: activiti-cloud-charts/charts/activiti-cloud-full-example
  name: activiti-cloud-full-example
  namespace: jx-staging
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
